language: groovy
jdk:
- openjdk11
sudo: false
branches:
  only:
  - main
  - develop
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
install:
  - travis_wait 20 ./gradlew assemble
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: WQn7cLUlAGTwCd6ivgk875SlTw5FJyKTYmCGHbfpdOTf404aZ5Iteax4pbohbSzyXi2LBfKON2TyrMG59G32pbtpXYZtGMbf0mxtgIHUyBzuH6b5VMucs1VU9j+YDOAadQ3J5nGO9aH4XN4fkxe85TyVMmEqB8JPtf4QP367E2n2DLj4xQtmyQMgBtmBCGQzJCzNNHmWBLK73cdUsh3KQbOJtvzMZErUmqzDMQxfEO7s+RweEcfzedeqvZJWohg1j/GE6r8Vm0o1s7W2zzr91vB/EqFRkquSho/vx5fSE5kBVhFPl0FDsKdnb04DgmMiyL3s3LDIaHLKPNwFwxDDWnBuzmEgzW3US2g6HYB9IhlYKFBiDsPBGbN9askhzstXWtN1XCBD9QVWKor2JAoQiKQyH0ydzDw8zIPTg8wEsAwDHP990HJZVhOLdQpJ5Cb3PlMef7BxDeTqlip5aeBDnFM1UTLdbS9uKLvjquqGLaqc21V2Za5GdCA+yk4wWbl8TMYmI0Ur0egfeFjvfC3nFZDYOScRnpXsBupCDQZE6E5weJVS5xvNgFiHjtvbfjDR4WshPOGy+AuhvheW1D1c8piLTBxd2A606UCRoTnsp/ZKRdKEQqcmQHQ8zyyl+KkMZM0R6CuSV98r9GoHtGEI8VBrrCF+8E5j5a0Z0hkVStw=
  - secure: VjqBvkEqT6L8pe7u2aquF5m+Eayz93zNFp8iPJ0hUZ2MFGCTdimmx8xWZX1o/Y1I2vFc0K+V26k0vQpPBV6pkozZdnd4a3NDLB3Q/8jM5nf41Y9rpGg2pmsNeKZq00FWvLnaRWUMIhQQEUuvsXI/iheq05BZNq+j3IcMJzVHx+dU07fo+jrqbl5XtDJD1qjdHjL3gmZpHkyMyo+5T21SbwanbXbOlA7rAnD3tuVHEd8BTXM1gSdrwFG9fJEi+0ijV94YApiC+/6vF0JeQuWN4ZA/ee0i989Q9hBvnwvmknyosfXEXKCoC7cQr09ShJGXdTkomG5V6MgrrZjumyoV/eezTgbZEUUq5orYMtrP/gSMU+9hWK47r/T0+vOJkn4KgTTrqA5wO33a0k+T5E//UU+nm0lzXuxMhlfFfPFa/Usx9PfxPOyo3CVC/Hg7UOg6/eiYtbBZeIlMwl1K4W8wFsKU2jUhmOE6FiN4DEGvMjcrbujJjeq91+2cazqVk6+YTKiBUCeImpCJWn3K3X6wdhfe2KSwUI5+XFoBpS6wJwDQTZc9JCaKOeKQv/XBlc+86wlOAijc9gQXExb+DrCsF5rL2jlJq3IY0/08r24ZSvWHdszqzuSooXVHmukSBSlvMof59VwZaKmDASBbQdLglE8JOec/fG4pJw/iXA0sxnQ=
